name: Desplegar a servidor

concurrency:
    group: production
    cancel-in-progress: true

on:
    push:
        branches:
            - master

jobs:
    despliegue:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Verificando repositorio
              uses: actions/checkout@v2

            - name: Desplegando repositorio
              uses: wlixcc/SFTP-Deploy-Action@v1.2.4
              with:
                  username: ${{ secrets.FTP_USERNAME }}
                  server: ${{ secrets.FTP_SERVER }}
                  port: ${{ secrets.FTP_PORT }}
                  local_path: "./Aplicacion/*"
                  remote_path: "/web"
                  sftp_only: true
                  password: ${{ secrets.FTP_PASSWORD }}
